interval_ms: 5000
query_batch_size: 1000
upsert_batch_size: 1000

source:
  connection_url: postgres://user:pass@localhost/mydb

destination:
  connection_url: clickhouse://default:@localhost/mydb

tables:
  - source: example_users
    dest: example_users
    cursors:
      - updated_at
      - id
  - source: example_orders
    cursors:
      - updated_at
      - id
  - source: example_transactions
    cursors:
      - created_at
      - id
